'use client'
import Link from 'next/link'
import { useEffect,useState } from 'react'
import { ArrowLeft,CheckCircle2,Circle,Loader2,XCircle } from 'lucide-react'
const stages=[['QUEUED','Queued'],['CRAWLING','Inspecting public pages'],['ANALYZING','Analyzing store signals'],['GENERATING_FINDINGS','Generating findings'],['SCORING','Calculating evidence-based scores'],['GENERATING_REPORT','Preparing your report'],['COMPLETED','Audit complete']] as const
type AuditStatus='DRAFT'|'QUEUED'|'CRAWLING'|'ANALYZING'|'GENERATING_FINDINGS'|'SCORING'|'GENERATING_REPORT'|'COMPLETED'|'CRAWL_FAILED'|'ANALYSIS_FAILED'|'AI_FAILED'|'REPORT_FAILED'|'CANCELLED'
type Audit={id:string;domain:string;store_url:string;status:AuditStatus;current_stage:string;overall_score:number|null;error_message:string|null;reportId:string|null}
export default function AuditStatusPage({params}:{params:Promise<{auditId:string}>}){
 const [audit,setAudit]=useState<Audit|null>(null);const [error,setError]=useState<string|null>(null)
 useEffect(()=>{let active=true;let timer:ReturnType<typeof setTimeout>|undefined;let processing=false;async function load(){try{const id=(await params).auditId;const r=await fetch(`/api/audits/${id}`,{cache:'no-store'});const d:{audit?:Audit;error?:string}=await r.json();if(!r.ok||!d.audit)throw new Error(d.error||'Unable to load audit.');if(!active)return;setAudit(d.audit);if(d.audit.status==='ANALYZING'&&!processing){processing=true;await fetch(`/api/audits/${id}/process`,{method:'POST'});processing=false;timer=setTimeout(load,800);return}if(!['COMPLETED','CRAWL_FAILED','ANALYSIS_FAILED','AI_FAILED','REPORT_FAILED','CANCELLED'].includes(d.audit.status))timer=setTimeout(load,2500)}catch(err){if(active)setError(err instanceof Error?err.message:'Unable to load audit.')}}load();return()=>{active=false;if(timer)clearTimeout(timer)}},[params])
 if(error)return <main className="flex min-h-screen items-center justify-center px-5"><div className="max-w-md text-center"><XCircle className="mx-auto h-10 w-10 text-red-500"/><h1 className="mt-4 text-2xl font-semibold">Couldn’t load this audit</h1><p className="mt-2 text-slate-600">{error}</p><Link href="/dashboard" className="mt-6 inline-flex rounded-xl bg-slate-950 px-5 py-3 font-medium text-white">Back to dashboard</Link></div></main>
 if(!audit)return <main className="flex min-h-screen items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-slate-500"/></main>
 const failed=audit.status.endsWith('_FAILED')||audit.status==='CANCELLED';const currentIndex=stages.findIndex(([key])=>key===audit.current_stage)
 return <main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-3xl px-5 py-10 lg:px-8"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-medium text-slate-600"><ArrowLeft className="h-4 w-4"/> Dashboard</Link><div className="mt-12"><p className="text-sm font-medium text-slate-500">{audit.status==='COMPLETED'?'Audit complete':'Audit in progress'}</p><h1 className="mt-2 break-all text-3xl font-semibold tracking-tight text-slate-950">{audit.domain}</h1><p className="mt-2 text-sm text-slate-500">{audit.store_url}</p><div className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">{failed?<div className="rounded-xl border border-red-200 bg-red-50 p-4"><p className="font-medium text-red-900">The audit could not be completed.</p><p className="mt-1 text-sm text-red-700">{audit.error_message||'An unexpected audit error occurred. Please try again.'}</p></div>:audit.status==='COMPLETED'?<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-5"><p className="font-semibold text-emerald-950">Audit complete.</p><p className="mt-1 text-sm text-emerald-800">Overall score: {audit.overall_score??'Insufficient evidence'}.</p>{audit.reportId&&<Link href={`/report/${audit.reportId}`} className="mt-4 inline-flex rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-medium text-white">Open full report</Link>}</div>:<><div className="flex items-center gap-3"><Loader2 className="h-5 w-5 animate-spin text-slate-700"/><p className="font-medium text-slate-900">{stages[Math.max(currentIndex,0)]?.[1]||'Processing audit…'}</p></div><div className="mt-7 space-y-4">{stages.map(([key,label],index)=><div key={key} className="flex items-center gap-3 text-sm"><span>{index<currentIndex?<CheckCircle2 className="h-5 w-5 text-emerald-600"/>:index===currentIndex?<Loader2 className="h-5 w-5 animate-spin text-slate-700"/>:<Circle className="h-5 w-5 text-slate-300"/>}</span><span className={index<=currentIndex?'font-medium text-slate-800':'text-slate-400'}>{label}</span></div>)}</div></>}</div></div></div></main>
}
