import type { SupabaseClient } from '@supabase/supabase-js'
import type { AuditSignals } from './analyzer'

const weights: Record<string, number> = { Conversion: 25, UX: 20, 'Product Experience': 15, Trust: 15, Copy: 10, SEO: 10, Mobile: 5 }
type Draft = { category:string; severity:'Critical'|'High'|'Medium'|'Low'; title:string; problem:string; evidence:Record<string,unknown>; whyItMatters:string; recommendedFix:string; implementation:string; priority:number; confidence:number; sourceUrl:string }

function pageFindings(url:string,s:AuditSignals):Draft[] {
  const f:Draft[]=[]; const add=(x:Omit<Draft,'sourceUrl'>)=>f.push({...x,sourceUrl:url})
  if(!s.titlePresent)add({category:'SEO',severity:'High',title:'Page title is missing or not reliably detectable',problem:'No usable HTML title was detected in the captured page.',evidence:{titlePresent:false},whyItMatters:'A descriptive title gives search engines and visitors clearer page context.',recommendedFix:'Add a unique, concise title describing the page intent.',implementation:'Set a page-specific document title in the head; do not reuse one generic title across the site.',priority:2,confidence:.98})
  if(!s.metaDescriptionPresent)add({category:'SEO',severity:'Medium',title:'Meta description is missing or not reliably detectable',problem:'No usable meta description was detected.',evidence:{metaDescriptionPresent:false},whyItMatters:'A useful description gives crawlers clearer context and can improve search-result presentation.',recommendedFix:'Add an accurate, distinct description to important indexable pages.',implementation:'Set the meta description in the page head and avoid site-wide duplication.',priority:5,confidence:.96})
  if(s.h1Count===0)add({category:'Copy',severity:'High',title:'No H1 heading was detected',problem:'The captured HTML contains no H1 heading.',evidence:{h1Count:0},whyItMatters:'The primary heading establishes the page topic and first textual anchor.',recommendedFix:'Add one clear H1 stating the page’s main intent or value proposition.',implementation:'Place one semantic H1 near the beginning of the main content and use H2/H3 for supporting sections.',priority:2,confidence:.99})
  if(s.h1Count>1)add({category:'Copy',severity:'Medium',title:'Multiple H1 headings were detected',problem:`The captured HTML contains ${s.h1Count} H1 headings.`,evidence:{h1Count:s.h1Count},whyItMatters:'Multiple primary headings can weaken the clarity of the page hierarchy.',recommendedFix:'Keep one primary H1 and convert secondary headings to H2/H3.',implementation:'Review templates and repeated components for unintended H1 elements.',priority:5,confidence:.99})
  if(s.imageCount>0&&s.imagesMissingAlt>0)add({category:'UX',severity:s.imagesMissingAlt>=3?'High':'Medium',title:'Some images are missing alt attributes',problem:`${s.imagesMissingAlt} of ${s.imageCount} detected images lack a usable alt attribute.`,evidence:{imageCount:s.imageCount,imagesMissingAlt:s.imagesMissingAlt},whyItMatters:'Meaningful alternative text improves accessibility and image context.',recommendedFix:'Add concise alt text to informative images and empty alt for decorative images.',implementation:'Prioritize product, category and promotional images; avoid keyword stuffing.',priority:s.imagesMissingAlt>=3?3:6,confidence:.99})
  if(s.ctaCount===0)add({category:'Conversion',severity:'High',title:'No recognizable conversion CTA was detected',problem:'No recognizable action such as Shop Now, Buy Now, Add to Cart or View Product was found.',evidence:{ctaCount:0},whyItMatters:'Visitors need a clear next step to move toward the intended conversion.',recommendedFix:'Add a prominent CTA aligned with the page intent.',implementation:'Use a specific action label and place it close to the relevant offer or product.',priority:1,confidence:.94})
  if(s.productSignals===0&&s.priceSignals===0)add({category:'Product Experience',severity:'Medium',title:'Product or pricing signals were not detected',problem:'No recognizable product-detail or price signals were found in the analyzed content.',evidence:{productSignals:0,priceSignals:0},whyItMatters:'Commercial visitors need enough product and pricing context to evaluate an offer.',recommendedFix:'If this is a commercial page, expose essential product information, availability and price clearly.',implementation:'Verify important purchase information is present in crawlable page content.',priority:4,confidence:.90})
  if(s.trustSignals===0)add({category:'Trust',severity:'Medium',title:'No common trust signals were detected',problem:'No recognizable public trust language such as returns, shipping, guarantee, secure checkout or support was detected.',evidence:{trustSignals:0},whyItMatters:'Clear policies and reassurance can reduce uncertainty at the buying decision.',recommendedFix:'Surface accurate policies and reassurance near the purchase decision.',implementation:'Expose only claims the business can substantiate, including shipping, returns, payment and support information.',priority:4,confidence:.90})
  return f
}

export async function generateFindings(supabase:SupabaseClient,auditId:string){
  const {data:pages,error}=await supabase.from('audit_pages').select('id,url,signals').eq('audit_id',auditId).eq('status','COMPLETED'); if(error)throw error
  if(!pages?.length)throw new Error('No successfully crawled pages are available for analysis.')
  const findings=pages.flatMap(p=>pageFindings(p.url,p.signals as AuditSignals).map(x=>({...x,pageId:p.id})))
  await supabase.from('audit_findings').delete().eq('audit_id',auditId); await supabase.from('audit_categories').delete().eq('audit_id',auditId)
  if(findings.length){const {error:e}=await supabase.from('audit_findings').insert(findings.map(x=>({audit_id:auditId,page_id:x.pageId,severity:x.severity,title:x.title,problem:x.problem,evidence:x.evidence,why_it_matters:x.whyItMatters,recommended_fix:x.recommendedFix,implementation:x.implementation,priority:x.priority,confidence:x.confidence,source_url:x.sourceUrl})));if(e)throw e}
  for(const category of Object.keys(weights)){const items=findings.filter(x=>x.category===category);const score=Math.max(0,Math.min(100,100-items.filter(x=>x.severity==='High'||x.severity==='Critical').length*24-items.filter(x=>x.severity==='Medium').length*10-items.filter(x=>x.severity==='Low').length*4));const {error:e}=await supabase.from('audit_categories').insert({audit_id:auditId,category,score,evidence_status:'OBSERVED',summary:items.length?`${items.length} evidence-based issue${items.length===1?'':'s'} detected across successfully crawled pages.`:'No material issue was detected by the current public-page rules.'});if(e)throw e}
  const {data:cats}=await supabase.from('audit_categories').select('category,score').eq('audit_id',auditId);const total=(cats??[]).reduce((n,c)=>n+(weights[c.category]??0),0);const overall=total?Math.round((cats??[]).reduce((n,c)=>n+Number(c.score)*(weights[c.category]??0),0)/total):null
  return {findingCount:findings.length,overallScore:overall}
}
