import Link from 'next/link'
import { ArrowRight, FileSearch, LogOut } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'

export default async function DashboardPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  const { data: audits } = user ? await supabase.from('audits').select('id, domain, status, overall_score, created_at').order('created_at', { ascending: false }).limit(5) : { data: [] }
  const name = user?.user_metadata?.full_name || user?.email?.split('@')[0] || 'there'

  return <main className="min-h-screen bg-slate-50"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/" className="font-semibold tracking-tight text-slate-950">StoreFix AI</Link><div className="flex items-center gap-4"><span className="hidden text-sm text-slate-500 sm:inline">{user?.email}</span><form action="/auth/signout" method="post"><button className="inline-flex items-center gap-2 text-sm font-medium text-slate-700"><LogOut className="h-4 w-4" /> Sign out</button></form></div></div></header><div className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-slate-500">Dashboard</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-950">Good to see you, {name}.</h1><p className="mt-2 text-slate-600">Run an evidence-based audit and turn findings into a practical fix plan.</p></div><Link href="/dashboard/audits/new" className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 py-3 font-medium text-white">New audit <ArrowRight className="h-4 w-4" /></Link></div><section className="mt-8 rounded-2xl border border-slate-200 bg-white p-7 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100"><FileSearch className="h-5 w-5 text-slate-700" /></div><div><h2 className="font-semibold text-slate-950">Recent audits</h2><p className="text-sm text-slate-500">Your latest audit activity.</p></div></div>{!audits?.length ? <div className="mt-8 rounded-xl border border-dashed border-slate-300 px-6 py-12 text-center"><p className="font-medium text-slate-800">No audits yet.</p><p className="mt-1 text-sm text-slate-500">Start with your store URL to create your first evidence-based report.</p><Link href="/dashboard/audits/new" className="mt-5 inline-flex rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-medium text-white">Start an audit</Link></div> : <div className="mt-6 divide-y divide-slate-100">{audits.map((audit) => <Link key={audit.id} href={`/dashboard/audits/${audit.id}`} className="flex items-center justify-between gap-4 py-4"><div><p className="font-medium text-slate-900">{audit.domain}</p><p className="text-sm text-slate-500">{new Date(audit.created_at).toLocaleDateString()}</p></div><span className="text-sm font-medium capitalize text-slate-600">{audit.status.replaceAll('_', ' ').toLowerCase()}</span></Link>)}</div>}</section></div></main>
}
